### ISSUE TITLE
1.15.2 experience dupe

### ISSUE THREAD

**Issue by karlovm** [zDevelopers/QuartzLib#24]
Players can remove the enchantments from maps (Amaury's edit: and any item with glow effect applied) and get exp.

**Comment by etysoftware** [comment]
Wait for fix

**Comment by etysoftware** [comment]
Please! Players want to use /tomap, but i can't enable the plugin because dupe exists

**Comment by AmauryCarrade** [comment]
Hi,

I don't have a lot of time, so this will be fixed when possible. I considered this as low-priority: you gain like 10 – 15 xp per map, that's really low so I don't think it's very critical.

I'll try to fix this as soon as possible but please remember I work for free on my free time, and I don't have much these days.

**Comment by karlovm** [comment]
Want fix! Players can dupe 40 levels in 1 minute!
