### ISSUE TITLE
ItemUtils: Update consumeItem to support dual-wielding

### ISSUE THREAD

**Issue by prokopyl** [zDevelopers/QuartzLib#41]
Right now the `ItemUtils.consumeItem()` helper method internally uses the `getItemInHand` Bukkit method, now deprecated because of dual-wielding.

Usages of `getItemInHand` should be removed, and the `consumeItem()` method should be changed to properly support dual-wielding, probably through an extra argument.

**Comment by AmauryCarrade** [comment]
For consistency with the Bukkit API, we could rename the existing method to `consumeItemInMainHand` (with a deprecated legacy fallback) and add another one `consumeItemInOffHand`

**Comment by prokopyl** [comment]
Considering we are making all of the breaking changes in this version, do we want to not deprecate methods and just remove them directly?

Otherwise yes, I agree we should probably split the methods following Bukkit's naming convention.

**Comment by AmauryCarrade** [comment]
Yeah we could do this. We need a migration guide anyway.
