### ISSUE TITLE
ItemUtils: Update damageItemInHand to use the Damageable ItemMeta API

### ISSUE THREAD

**Issue by prokopyl** [zDevelopers/QuartzLib#42]
The `ItemUtils.damageItemInHand()` method still uses damage values, and should use the [`Damageable`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/Damageable.html) ItemMeta instead.

**Comment by AmauryCarrade** [comment]
We may want to rename it `damageItemInMainHand` for consistency with Bukkit? Especially if we add a `damageItemInOffHand`.

**Comment by prokopyl** [comment]
Either that, or considering the item is actually given to the method for damaging/breaking, it can probably just figure it out?

Actually, now that I look at it, the `damageItemInHand` doesn't seem to care if the item is in the player's hand or not. So it should probably be renamed instead?

**Comment by AmauryCarrade** [comment]
I think `ItemUtils.damageItem()` would suffice, yes. At the beginning, I thought that the method automatically took the object in hand, if there was one (bad memory...).
