### ISSUE TITLE
Remove reflection-based DualWielding implementation

### ISSUE THREAD

**Issue by prokopyl** [zDevelopers/QuartzLib#43]
The `DualWielding` utility class mainly uses Reflection to call normal Bukkit APIs in order to be compatible with pre-1.9 versions, however since we're targeting 1.15 for a minimum version, we can now remove reflection completely.

It's also possible that once reflection is removed, there would be little use in keeping this utility class.

**Comment by AmauryCarrade** [comment]
Except for the [`getHoldingHand' method](https://zdevelopers.github.io/QuartzLib/fr/zcraft/quartzlib/tools/items/DualWielding.html#getHoldingHand-org.bukkit.entity.Player-org.bukkit.inventory.ItemStack-), I'm not sure any oft his is still needed.

This may as well be moved to our inventory utils.
